### ISSUE TITLE
Do you know how to calculate the accuracy of the Count, Exists, Compare Numbers, etc

### ISSUE THREAD

**Issue by ToTheBeginning** [mesnico/RelationNetworks-CLEVR#6]
To the best of my knowledge, most repos on github only report the overall accuracy, but I want the same format as the paper reports.

Can you help me, it will be very helpful for me!

**Comment by mesnico** [comment]
Hi @ToTheBeginning 
You can find the answer [here](https://github.com/facebookresearch/clevr-dataset-gen/issues/7)

Basically, this info is embedded in JSON files encoding questions in the CLEVR dataset. For each question, a functional program formally encodes the question. The last element of the program determines the type of the question.

It should not be difficult to classify questions on the basis of that piece of information.
Hope it helps!

**Comment by ToTheBeginning** [comment]
Thanks.
That is very helpful!
