### ISSUE TITLE
AttributeError: Can't get attribute '_rebuild_tensor_v2' on <module 'torch._utils' from '/home/GoodPaperCode/RelationNetworks-CLEVR-master/env/lib/python3.6/site-packages/torch/_utils.py'>

### ISSUE THREAD

**Issue by lizhenstat** [mesnico/RelationNetworks-CLEVR#9]
Hi, thanks for sharing of your code!!!
I have followed the instruction and build the virtualenv of pytorch-0.3.1
However, when running the following line
```python
python train.py --clevr-dir /home/Data/CLEVR/CLEVR_v1.0 --model 'original-sd' | tee logfile.log
```
The terminal gives out the following error:
```python
Traceback (most recent call last):
  File "train.py", line 418, in <module>
Loaded hyperparameters from configuration config.json, model: original-sd: {'state_description': True, 'g_layers': [512, 512, 512, 512], 'question_injection_position': 0, 'f_fc1': 512, 'f_fc2': 1024, 'dropout': 0.05, 'lstm_hidden': 256, 'lstm_word_emb': 32, 'rl_in_size': 14}
Building word dictionaries from all the words in the dataset...
==> using cached dictionaries: /home/Data/CLEVR/CLEVR_v1.0/questions/CLEVR_built_dictionaries.pkl
Word dictionary completed!
Initializing CLEVR dataset...
==> using cached questions: /home/Data/CLEVR/CLEVR_v1.0/questions/CLEVR_train_questions.pkl
==> using cached scenes: /home/Data/CLEVR/CLEVR_v1.0/scenes/CLEVR_train_scenes.pkl
    main(args)
  File "train.py", line 247, in main
    clevr_dataset_train, clevr_dataset_test  = initialize_dataset(args.clevr_dir, dictionaries, hyp['state_description'])
  File "train.py", line 194, in initialize_dataset
    clevr_dataset_train = ClevrDatasetStateDescription(clevr_dir, True, dictionaries)
  File "/home/GoodPaperCode/RelationNetworks-CLEVR-master/clevr_dataset_connector.py", line 98, in __init__
    self.objects = pickle.load(f)
AttributeError: Can't get attribute '_rebuild_tensor_v2' on <module 'torch._utils' from '/home/GoodPaperCode/RelationNetworks-CLEVR-master/env/lib/python3.6/site-packages/torch/_utils.py'>
```

I checked the website and find the related [answer](https://github.com/pytorch/pytorch/issues/5729)
Do you have any idea how can I fix this?

Any help would be appreciated and thanks for your time!

**Comment by mesnico** [comment]
Hi @lizhenstat,
it seems you initially used a later version of PyTorch for creating the .pkl scene cache files. You can try to manually delete them (they are placed in ```CLEVR_v1.0/scenes```) and then re-run the ```train.py``` script. They will be automatically re-generated. Unfortunately, I had no time to do the necessary changes for making the code to work with PyTorch >1.0. Make sure you have version 0.3.1 and that you are running the scripts from the inside of your virtualenv.
Let me know

**Comment by lizhenstat** [comment]
@mesnico Hi, thanks for your quick reply! ^_^
I deleted the previous training checkpoint file and  it works now!!

Best wishes
